name: flip_book_example
version: 1.0.0+1
description: An example project showcasing flip_book.

# The following line prevents the package from being accidentally published to
publish_to: 'none'

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.3.1
  cupertino_icons: ^1.0.2
  flip_book:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/pages_data/he/
  uses-material-design: true
