name: flip_book
description: flip_book is a Flutter flip book component. `FlipBook` Widget + `FlipBookController` for controlling it anywhere.
version: 0.0.1+3
homepage: https://github.com/doradsoft/flutter_flip_book

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  provider: ^6.0.2
  tuple: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: null
flutter_intl:
  enabled: true
